//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Formula.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="FormulaParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IFormulaListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormula([NotNull] FormulaParser.FormulaContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.formula"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormula([NotNull] FormulaParser.FormulaContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>MulExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMulExpr([NotNull] FormulaParser.MulExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>MulExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMulExpr([NotNull] FormulaParser.MulExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EqualExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualExpr([NotNull] FormulaParser.EqualExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EqualExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualExpr([NotNull] FormulaParser.EqualExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>SubExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSubExpr([NotNull] FormulaParser.SubExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>SubExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSubExpr([NotNull] FormulaParser.SubExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>GreaterExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGreaterExpr([NotNull] FormulaParser.GreaterExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>GreaterExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGreaterExpr([NotNull] FormulaParser.GreaterExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>GreaterEqualExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGreaterEqualExpr([NotNull] FormulaParser.GreaterEqualExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>GreaterEqualExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGreaterEqualExpr([NotNull] FormulaParser.GreaterEqualExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AddExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAddExpr([NotNull] FormulaParser.AddExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AddExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAddExpr([NotNull] FormulaParser.AddExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NotEqualExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotEqualExpr([NotNull] FormulaParser.NotEqualExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NotEqualExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotEqualExpr([NotNull] FormulaParser.NotEqualExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LessExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLessExpr([NotNull] FormulaParser.LessExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LessExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLessExpr([NotNull] FormulaParser.LessExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LessEqualExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLessEqualExpr([NotNull] FormulaParser.LessEqualExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LessEqualExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLessEqualExpr([NotNull] FormulaParser.LessEqualExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>PowerExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPowerExpr([NotNull] FormulaParser.PowerExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>PowerExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPowerExpr([NotNull] FormulaParser.PowerExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>DivExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDivExpr([NotNull] FormulaParser.DivExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>DivExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDivExpr([NotNull] FormulaParser.DivExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>CellExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCellExpr([NotNull] FormulaParser.CellExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>CellExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCellExpr([NotNull] FormulaParser.CellExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NumberExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumberExpr([NotNull] FormulaParser.NumberExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NumberExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumberExpr([NotNull] FormulaParser.NumberExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryPlusExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryPlusExpr([NotNull] FormulaParser.UnaryPlusExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryPlusExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryPlusExpr([NotNull] FormulaParser.UnaryPlusExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ParensExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParensExpr([NotNull] FormulaParser.ParensExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ParensExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParensExpr([NotNull] FormulaParser.ParensExprContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryMinusExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryMinusExpr([NotNull] FormulaParser.UnaryMinusExprContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryMinusExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryMinusExpr([NotNull] FormulaParser.UnaryMinusExprContext context);
}
