//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Formula.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IFormulaListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class FormulaBaseListener : IFormulaListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="FormulaParser.formula"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFormula([NotNull] FormulaParser.FormulaContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="FormulaParser.formula"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFormula([NotNull] FormulaParser.FormulaContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>MulExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMulExpr([NotNull] FormulaParser.MulExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>MulExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMulExpr([NotNull] FormulaParser.MulExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>EqualExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEqualExpr([NotNull] FormulaParser.EqualExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>EqualExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEqualExpr([NotNull] FormulaParser.EqualExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>SubExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSubExpr([NotNull] FormulaParser.SubExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>SubExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSubExpr([NotNull] FormulaParser.SubExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>GreaterExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGreaterExpr([NotNull] FormulaParser.GreaterExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>GreaterExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGreaterExpr([NotNull] FormulaParser.GreaterExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>GreaterEqualExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGreaterEqualExpr([NotNull] FormulaParser.GreaterEqualExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>GreaterEqualExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGreaterEqualExpr([NotNull] FormulaParser.GreaterEqualExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AddExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAddExpr([NotNull] FormulaParser.AddExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AddExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAddExpr([NotNull] FormulaParser.AddExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NotEqualExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNotEqualExpr([NotNull] FormulaParser.NotEqualExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NotEqualExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNotEqualExpr([NotNull] FormulaParser.NotEqualExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LessExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLessExpr([NotNull] FormulaParser.LessExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LessExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLessExpr([NotNull] FormulaParser.LessExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>LessEqualExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLessEqualExpr([NotNull] FormulaParser.LessEqualExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>LessEqualExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLessEqualExpr([NotNull] FormulaParser.LessEqualExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>PowerExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPowerExpr([NotNull] FormulaParser.PowerExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>PowerExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPowerExpr([NotNull] FormulaParser.PowerExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>DivExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDivExpr([NotNull] FormulaParser.DivExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>DivExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDivExpr([NotNull] FormulaParser.DivExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>CellExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCellExpr([NotNull] FormulaParser.CellExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>CellExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCellExpr([NotNull] FormulaParser.CellExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>NumberExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumberExpr([NotNull] FormulaParser.NumberExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>NumberExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumberExpr([NotNull] FormulaParser.NumberExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryPlusExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryPlusExpr([NotNull] FormulaParser.UnaryPlusExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryPlusExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryPlusExpr([NotNull] FormulaParser.UnaryPlusExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ParensExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParensExpr([NotNull] FormulaParser.ParensExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ParensExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParensExpr([NotNull] FormulaParser.ParensExprContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryMinusExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryMinusExpr([NotNull] FormulaParser.UnaryMinusExprContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryMinusExpr</c>
	/// labeled alternative in <see cref="FormulaParser.expr"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryMinusExpr([NotNull] FormulaParser.UnaryMinusExprContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
